import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Films from '../data/ListOfFilms.json'
import axios from 'axios'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [filmImage, setFilmImage] = useState([])
  const [filmName, setFilmName] = useState([])

const getImages = async () => {
axios.get(`https://www.googleapis.com/customsearch/v1?key=AIzaSyDxjct7m3ELLu-_tAqZxpaZMaAqRPcY2N8&cx=017576662512468239146:omuauf_lfve&q=lectures&searchType=image`)
.then((response) => {
  console.log(response.data)
})
.catch((error) => {
  console.log(error)
})
}

//filter through the array



return (
    <>
      <Head>
        <title>Higher Lower on Times a Movie says Fuck</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Higher or Lower
        </h1>
        <p className={styles.description}>
          Which movie says Fuck more?
        </p>
        <div className={styles.grid}>
          <Image src='' height={200} width={200}>

          </Image>
          {/* {Films.map((film) => (
            <a key={film.id} href="#" className={styles.card}>
              <h3>{film.Film} &rarr;</h3>
              <p>{film.Count}</p>
              <p>{film.Rank}</p>

            </a>
          ))} */}

          //show 1 random film 
          
          <button onClick={() => getImages()}>
            Get Images
          </button>
        </div>
      </main>
    </>
  )
}
